apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: infra
  source:
    directory:
      recurse: true
    path: cluster/namespaces
    repoURL: https://github.com/basivireddy/openshift-gitops-argocd.git
    targetRevision: main
